services:
  ros-ouster:
    build:
      context: ./.devcontainer
      args:
        GID: 1000
        UID: 1000
    image: ros-ouster
    container_name: ros-ouster
    hostname: ros-ouster
    init: true
    network_mode: host
    environment:
      - TZ=Europe/Warsaw
      - ROS_ENABLE_AUTOSTART=0
      - ROS_BUILD_ON_STARTUP=on-failure
    volumes:
      - type: bind
        source: ./
        target: /home/rex/raptor_ws
        bind:
          create_host_path: true
      - type: bind
        source: ./.devcontainer/rex
        target: /etc/init.d/rex
        bind:
          create_host_path: true
      - "./.devcontainer/sshd_config:/etc/ssh/sshd_config"
    restart: unless-stopped
